resources:
  - namespace.yaml
  - true-roots-backend-deployment.yaml
  - true-roots-backend-service.yaml
  - db-deployment.yaml
  - db-service.yaml
  - true-roots-frondtend-deployment.yaml
  - true-roots-frondtend-ingress.yaml
  - true-roots-frondtend-service.yaml

images:
  - name: IMAGE_TAG_FR
    newName: "${IMAGE_TAG_FE}"
  - name: IMAGE_TAG_BK
    newName: "${IMAGE_TAG_BE}"

namespace: brc
